name: Deployment Pipelline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Tests
        run: npm run test
      - name: E2E Tests
        uses: cypress-io/github-action@v4
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000